#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# record_backup_video.sh
#
# PreOpReel — record the locked 2-minute demo via Playwright headless Chromium.
# Output: docs/demo-backup.mp4 + docs/demo-backup.fingerprint.json
# Auto-stages and commits both. Hard-required by 5 PM demo day (CLAUDE.md).
#
# Owner: Demo Ops Dev (Phase 3, Section C of docs/plans/04-frontend-and-demo.md;
# Mara B.9 mitigation — fingerprint JSON is the second-eyes validation surface).
#
# Promo: BUTTERBASE0502 (ALL CAPS) / Submission: butterbase0502 (lowercase).
#
# Dependencies (NOT installed by this script — document only):
#   - node 20+
#   - npx playwright install chromium  (one-time, in apps/web/)
#   - ffmpeg (for transcoding webm -> mp4 + frame extraction)
#   - python 3.11+ with hashlib (stdlib only, used by verify_backup_video.py)
#
# Exit codes:
#   0 — recorded, fingerprinted, staged, committed
#   1 — preconditions failed (next dev not up, demo not pre-staged)
#   2 — recording failed
#   3 — fingerprinting failed
#   4 — git commit failed
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="${REPO_ROOT}/docs"
OUT_MP4="${DOCS_DIR}/demo-backup.mp4"
OUT_FP="${DOCS_DIR}/demo-backup.fingerprint.json"
TMP_DIR="$(mktemp -d -t preopreel-demo.XXXXXX)"
RECORDER_JS="${TMP_DIR}/record.js"

trap 'rm -rf "${TMP_DIR}"' EXIT

URL="${PREOPREEL_DEMO_URL:-http://localhost:3000/forge?demo=hip-replacement}"

# ── Preconditions ────────────────────────────────────────────────────────────
echo "[preflight] target URL: ${URL}"
if ! curl -sSf -o /dev/null --max-time 5 "${URL%%\?*}"; then
  echo "ERROR: dev server not reachable at ${URL%%\?*}" >&2
  echo "       run: npm run dev   (and ensure DEMO_MODE=replay)" >&2
  exit 1
fi
mkdir -p "${DOCS_DIR}"

# ── Playwright recorder script (heredoc — Node, ESM-style ok with .js) ───────
cat > "${RECORDER_JS}" <<'JS'
// Generated by record_backup_video.sh — Playwright headless recorder.
// Walks the locked 2-minute beat-by-beat. Outputs a webm; ffmpeg transcodes.
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const URL = process.env.PREOPREEL_DEMO_URL;
const OUT_DIR = process.env.PREOPREEL_OUT_DIR;

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    viewport: { width: 1920, height: 1080 },
    recordVideo: { dir: OUT_DIR, size: { width: 1920, height: 1080 } },
  });
  const page = await context.newPage();
  await page.goto(URL, { waitUntil: 'domcontentloaded' });

  // 0:00 — landing on /forge?demo=hip-replacement; allow AnatomyGraphViewer
  // to populate (10s).
  await page.waitForTimeout(10_000);

  // 0:10 — open CriticHud panel (15s). data-test attributes are wired by
  // Frontend Dev's components (CriticHud.tsx).
  try {
    await page.locator('[data-test="critic-hud-tab"]').click({ timeout: 4_000 });
  } catch {} // tolerate if the panel is already visible
  await page.waitForTimeout(15_000);

  // 0:25 — wait for Beat-3 reject/regen (40s). Lyra fixture has the deliberate
  // 0.71 -> 0.86 sequence on shot_3.
  await page.waitForTimeout(40_000);

  // 1:05 — open the audit PDF (60s on it)
  try {
    await page.locator('[data-test="audit-pdf-button"]').click({ timeout: 4_000 });
  } catch {}
  await page.waitForTimeout(60_000);

  // 2:05 — full-screen MP4
  try {
    await page.locator('[data-test="explainer-fullscreen"]').click({ timeout: 4_000 });
  } catch {}
  await page.waitForTimeout(75_000);

  // 3:20 — let it play to end (120s)
  await page.waitForTimeout(120_000);

  await context.close();
  await browser.close();

  // Find the latest .webm in OUT_DIR
  const entries = fs.readdirSync(OUT_DIR).filter(f => f.endsWith('.webm'));
  if (entries.length === 0) {
    console.error('No .webm produced by Playwright');
    process.exit(2);
  }
  entries.sort();
  const webm = path.join(OUT_DIR, entries[entries.length - 1]);
  console.log(JSON.stringify({ webm }));
})().catch((e) => { console.error(e); process.exit(2); });
JS

# ── Run the recorder ─────────────────────────────────────────────────────────
echo "[record] launching headless Chromium (this takes ~5 minutes wall-clock)…"
PREOPREEL_DEMO_URL="${URL}" PREOPREEL_OUT_DIR="${TMP_DIR}" node "${RECORDER_JS}" \
  > "${TMP_DIR}/recorder.out.json" || { echo "ERROR: recorder failed" >&2; exit 2; }

WEBM_PATH="$(node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).webm)' "${TMP_DIR}/recorder.out.json")"
if [[ ! -f "${WEBM_PATH}" ]]; then
  echo "ERROR: webm path not found: ${WEBM_PATH}" >&2
  exit 2
fi

# ── Transcode to MP4 (1920x1080, H.264, AAC) ────────────────────────────────
echo "[ffmpeg] transcoding to ${OUT_MP4}"
ffmpeg -y -loglevel error -i "${WEBM_PATH}" \
  -vf "scale=1920:1080" \
  -c:v libx264 -preset medium -crf 22 -profile:v high -level 4.0 \
  -c:a aac -b:a 192k -movflags +faststart \
  "${OUT_MP4}" || { echo "ERROR: ffmpeg failed" >&2; exit 2; }

# ── Fingerprint frames at 0:00, 0:30, 0:50, 1:00, 1:30, 1:55 (Mara B.9) ──────
echo "[fingerprint] hashing frames at six checkpoints"
TIMESTAMPS=(0 30 50 60 90 115)
NODES=()
for ts in "${TIMESTAMPS[@]}"; do
  PNG="${TMP_DIR}/frame_${ts}.png"
  ffmpeg -y -loglevel error -ss "${ts}" -i "${OUT_MP4}" \
    -frames:v 1 -vf "scale=320:180" "${PNG}" \
    || { echo "ERROR: frame extract at ${ts}s failed" >&2; exit 3; }
  HASH="$(shasum -a 256 "${PNG}" | awk '{print $1}')"
  NODES+=("    {\"timestamp_seconds\": ${ts}, \"sha256\": \"${HASH}\"}")
done

JOINED="$(IFS=$',\n'; echo "${NODES[*]}")"
cat > "${OUT_FP}" <<JSON
{
  "video_path": "docs/demo-backup.mp4",
  "checkpoint_size": "320x180",
  "checkpoints": [
${JOINED}
  ],
  "promo_code": "BUTTERBASE0502",
  "submission_code": "butterbase0502",
  "recorded_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
JSON

echo "[ok] wrote ${OUT_MP4}"
echo "[ok] wrote ${OUT_FP}"

# ── Auto-stage + commit ─────────────────────────────────────────────────────
cd "${REPO_ROOT}"
git add docs/demo-backup.mp4 docs/demo-backup.fingerprint.json
if ! git commit -m "demo: backup video for $(date +%Y-%m-%d)"; then
  echo "ERROR: git commit failed (nothing to commit, or pre-commit blocked)" >&2
  exit 4
fi
echo "[ok] committed backup video + fingerprint"

exit 0
